import 'package:flutter/material.dart';
import 'chart_item.dart';
import 'fl_chart/fl_basic_charts.dart';
import 'fl_chart/fl_advanced_charts.dart';
import 'syncfusion/sf_basic_charts.dart';
import 'syncfusion/sf_advanced_charts.dart';
import 'graphic_lib/gr_basic_charts.dart';
import 'graphic_lib/gr_advanced_charts.dart';
import 'custom_painter/cp_basic_charts.dart';
import 'custom_painter/cp_advanced_charts.dart';

class ChartRegistry {
  static final List<ChartLibrary> libraries = [
    ChartLibrary(
      id: 'fl_chart',
      name: 'fl_chart',
      description: 'La librería más popular de Flutter para gráficas',
      color: const Color(0xFF1565C0),
      icon: Icons.show_chart,
      basic: _flBasic,
      advanced: _flAdvanced,
    ),
    ChartLibrary(
      id: 'syncfusion',
      name: 'Syncfusion',
      description: 'Suite profesional con +30 tipos de gráficas',
      color: const Color(0xFF6A1B9A),
      icon: Icons.pie_chart,
      basic: _sfBasic,
      advanced: _sfAdvanced,
    ),
    ChartLibrary(
      id: 'graphic',
      name: 'Graphic',
      description: 'Grammar of Graphics inspirado en ggplot2',
      color: const Color(0xFF2E7D32),
      icon: Icons.scatter_plot,
      basic: _grBasic,
      advanced: _grAdvanced,
    ),
    ChartLibrary(
      id: 'custom_painter',
      name: 'CustomPainter',
      description: 'Gráficas nativas con Canvas de Flutter',
      color: const Color(0xFFBF360C),
      icon: Icons.brush,
      basic: _cpBasic,
      advanced: _cpAdvanced,
    ),
  ];

  // ── fl_chart Basic (43) ─────────────────────────────────────────────────────
  static final List<ChartItem> _flBasic = [
    ChartItem(id:'fl_b01', title:'Stats de Bulbasaur',          subtitle:'Barras verticales · 6 stats base',               category:'bar',       builder:() => const FlB01()),
    ChartItem(id:'fl_b02', title:'Stats de Mewtwo',             subtitle:'Barras verticales · Pokémon legendario',          category:'bar',       builder:() => const FlB02()),
    ChartItem(id:'fl_b03', title:'Bulbasaur vs Charmander',     subtitle:'Barras agrupadas · Comparativa de stats',         category:'bar',       builder:() => const FlB03()),
    ChartItem(id:'fl_b04', title:'Top 5 por Ataque',            subtitle:'Barras horizontales · Ranking ofensivo',          category:'bar',       builder:() => const FlB04()),
    ChartItem(id:'fl_b05', title:'Top 5 por Defensa',           subtitle:'Barras horizontales · Ranking defensivo',         category:'bar',       builder:() => const FlB05()),
    ChartItem(id:'fl_b06', title:'Top 5 por HP',                subtitle:'Barras horizontales · Ranking de vida',           category:'bar',       builder:() => const FlB06()),
    ChartItem(id:'fl_b07', title:'Top 5 por Velocidad',         subtitle:'Barras horizontales · Ranking de velocidad',      category:'bar',       builder:() => const FlB07()),
    ChartItem(id:'fl_b08', title:'Fuego vs Agua vs Planta',     subtitle:'Barras agrupadas · Stats promedio por tipo',      category:'bar',       builder:() => const FlB08()),
    ChartItem(id:'fl_b09', title:'Evolución HP Bulbasaur',      subtitle:'Línea · Bulbasaur → Ivysaur → Venusaur',          category:'line',      builder:() => const FlB09()),
    ChartItem(id:'fl_b10', title:'Evolución Ataque Charmander', subtitle:'Línea · Charmander → Charizard',                  category:'line',      builder:() => const FlB10()),
    ChartItem(id:'fl_b11', title:'Evolución Defensa Squirtle',  subtitle:'Línea · Squirtle → Blastoise',                    category:'line',      builder:() => const FlB11()),
    ChartItem(id:'fl_b12', title:'HP Primeros 20 Pokémon',      subtitle:'Línea · Valores de HP Gen I',                     category:'line',      builder:() => const FlB12()),
    ChartItem(id:'fl_b13', title:'Velocidad Primeros 20',       subtitle:'Línea · Valores de velocidad Gen I',              category:'line',      builder:() => const FlB13()),
    ChartItem(id:'fl_b14', title:'Distribución Tipos Gen I',    subtitle:'Pastel · 8 categorías principales',               category:'pie',       builder:() => const FlB14()),
    ChartItem(id:'fl_b15', title:'Top 5 Tipos más Comunes',     subtitle:'Pastel · Los 5 tipos más frecuentes',             category:'pie',       builder:() => const FlB15()),
    ChartItem(id:'fl_b16', title:'Tipos Gen I (Donut)',          subtitle:'Donut · Proporción de cada tipo',                 category:'pie',       builder:() => const FlB16()),
    ChartItem(id:'fl_b17', title:'1 Tipo vs 2 Tipos',           subtitle:'Donut · Pokémon monotipo vs bitipo',              category:'pie',       builder:() => const FlB17()),
    ChartItem(id:'fl_b18', title:'Legendarios vs Normales',     subtitle:'Pastel · 5 legendarios vs 146 regulares',         category:'pie',       builder:() => const FlB18()),
    ChartItem(id:'fl_b19', title:'HP de los Starters',          subtitle:'Área · Los 9 starters de Gen I',                  category:'area',      builder:() => const FlB19()),
    ChartItem(id:'fl_b20', title:'Ataque Primeros 15',          subtitle:'Área · Evolución del ataque',                     category:'area',      builder:() => const FlB20()),
    ChartItem(id:'fl_b21', title:'HP Comparativa Starters',     subtitle:'Área multi-serie · Tres líneas evolutivas',       category:'area',      builder:() => const FlB21()),
    ChartItem(id:'fl_b22', title:'Defensa Primeros 20',         subtitle:'Área · Valores de defensa',                       category:'area',      builder:() => const FlB22()),
    ChartItem(id:'fl_b23', title:'Sp. Ataque Primeros 20',      subtitle:'Área · Ataque especial',                          category:'area',      builder:() => const FlB23()),
    ChartItem(id:'fl_b24', title:'Distribución HP Gen I',       subtitle:'Histograma · Rangos de puntos de vida',           category:'histogram', builder:() => const FlB24()),
    ChartItem(id:'fl_b25', title:'Distribución Ataque',         subtitle:'Histograma · Rangos de ataque',                   category:'histogram', builder:() => const FlB25()),
    ChartItem(id:'fl_b26', title:'Distribución Defensa',        subtitle:'Histograma · Rangos de defensa',                  category:'histogram', builder:() => const FlB26()),
    ChartItem(id:'fl_b27', title:'Distribución Velocidad',      subtitle:'Histograma · Rangos de velocidad',                category:'histogram', builder:() => const FlB27()),
    ChartItem(id:'fl_b28', title:'Ataque vs Defensa',           subtitle:'Dispersión · 40 Pokémon representativos',         category:'scatter',   builder:() => const FlB28()),
    ChartItem(id:'fl_b29', title:'HP vs Velocidad',             subtitle:'Dispersión · HP frente a velocidad',              category:'scatter',   builder:() => const FlB29()),
    ChartItem(id:'fl_b30', title:'Ataque vs Velocidad',         subtitle:'Dispersión · Perfil ofensivo',                    category:'scatter',   builder:() => const FlB30()),
    ChartItem(id:'fl_b31', title:'Sp.Atk vs Sp.Def',           subtitle:'Dispersión · Stats especiales',                   category:'scatter',   builder:() => const FlB31()),
    ChartItem(id:'fl_b32', title:'HP vs Ataque',                subtitle:'Burbuja · Tamaño representa Defensa',             category:'bubble',    builder:() => const FlB32()),
    ChartItem(id:'fl_b33', title:'Velocidad vs Ataque',         subtitle:'Burbuja · Tamaño representa HP',                  category:'bubble',    builder:() => const FlB33()),
    ChartItem(id:'fl_b34', title:'HP vs Sp.Atk',               subtitle:'Burbuja · Tamaño representa Velocidad',           category:'bubble',    builder:() => const FlB34()),
    ChartItem(id:'fl_b35', title:'Stats de Pikachu',            subtitle:'Radar · 6 dimensiones del ratón eléctrico',       category:'radar',     builder:() => const FlB35()),
    ChartItem(id:'fl_b36', title:'Stats de Mewtwo',             subtitle:'Radar · El Pokémon más poderoso',                 category:'radar',     builder:() => const FlB36()),
    ChartItem(id:'fl_b37', title:'Charizard vs Blastoise',      subtitle:'Radar multi-serie · Comparativa directa',         category:'radar',     builder:() => const FlB37()),
    ChartItem(id:'fl_b38', title:'Fuego avg vs Agua avg',       subtitle:'Radar · Promedios por tipo',                      category:'radar',     builder:() => const FlB38()),
    ChartItem(id:'fl_b39', title:'Correlación Stats Gen I',     subtitle:'Mapa de calor · Matriz 6×6',                      category:'heatmap',   builder:() => const FlB39()),
    ChartItem(id:'fl_b40', title:'Stats Promedio por Tipo',     subtitle:'Mapa de calor · 6 tipos × 6 stats',              category:'heatmap',   builder:() => const FlB40()),
    ChartItem(id:'fl_b41', title:'Stats + Línea Promedio',      subtitle:'Combinado · Barras con tendencia',                category:'combined',  builder:() => const FlB41()),
    ChartItem(id:'fl_b42', title:'HP Área + Velocidad Scatter', subtitle:'Combinado · Dos tipos de gráfica',                category:'combined',  builder:() => const FlB42()),
    ChartItem(id:'fl_b43', title:'Dashboard Pokémon',           subtitle:'Combinado · Stats, tipo y total',                 category:'combined',  builder:() => const FlB43()),
  ];

  // ── fl_chart Advanced (36) ──────────────────────────────────────────────────
  static final List<ChartItem> _flAdvanced = [
    ChartItem(id:'fl_a01', title:'Barras Animadas',          subtitle:'Entrada con animación suave por stat',          category:'bar',      builder:() => const FlA01()),
    ChartItem(id:'fl_a02', title:'Selector de Pokémon',      subtitle:'Barras interactivas con dropdown',              category:'bar',      builder:() => const FlA02()),
    ChartItem(id:'fl_a03', title:'Barras con Tooltip',       subtitle:'Stats detallados al tocar la barra',            category:'bar',      builder:() => const FlA03()),
    ChartItem(id:'fl_a04', title:'Diferencia vs Promedio',   subtitle:'Barras positivas y negativas',                  category:'bar',      builder:() => const FlA04()),
    ChartItem(id:'fl_a05', title:'Composición 100%',         subtitle:'Barras apiladas normalizadas',                  category:'bar',      builder:() => const FlA05()),
    ChartItem(id:'fl_a06', title:'Ranking Dinámico Top 10',  subtitle:'Barras ordenadas por stat seleccionado',        category:'bar',      builder:() => const FlA06()),
    ChartItem(id:'fl_a07', title:'Línea con Zoom/Pan',       subtitle:'Navegación táctil interactiva',                 category:'line',     builder:() => const FlA07()),
    ChartItem(id:'fl_a08', title:'Multi-serie 6 Stats',      subtitle:'Todas las dimensiones a la vez',                category:'line',     builder:() => const FlA08()),
    ChartItem(id:'fl_a09', title:'Línea con Gradiente',      subtitle:'HP con fill degradado animado',                 category:'line',     builder:() => const FlA09()),
    ChartItem(id:'fl_a10', title:'Actualización Animada',    subtitle:'Datos simulados en tiempo real',                category:'line',     builder:() => const FlA10()),
    ChartItem(id:'fl_a11', title:'Comparativa Evolutiva',    subtitle:'Selector de línea evolutiva',                   category:'line',     builder:() => const FlA11()),
    ChartItem(id:'fl_a12', title:'Pastel Animado',           subtitle:'Entrada con animación circular',                category:'pie',      builder:() => const FlA12()),
    ChartItem(id:'fl_a13', title:'Leyenda Interactiva',      subtitle:'Toggle de secciones al tocar',                  category:'pie',      builder:() => const FlA13()),
    ChartItem(id:'fl_a14', title:'Donut con Estadística',    subtitle:'Total de stats en el centro',                   category:'pie',      builder:() => const FlA14()),
    ChartItem(id:'fl_a15', title:'Donut Multi-nivel',        subtitle:'Dos anillos de datos concéntricos',             category:'pie',      builder:() => const FlA15()),
    ChartItem(id:'fl_a16', title:'Semi-Donut Gauge',         subtitle:'Estilo medidor semicircular',                   category:'pie',      builder:() => const FlA16()),
    ChartItem(id:'fl_a17', title:'Scatter por Tipo',         subtitle:'Puntos coloreados por tipo Pokémon',            category:'scatter',  builder:() => const FlA17()),
    ChartItem(id:'fl_a18', title:'Scatter con Detalle',      subtitle:'Tap para ver nombre del Pokémon',               category:'scatter',  builder:() => const FlA18()),
    ChartItem(id:'fl_a19', title:'Scatter Animado',          subtitle:'Transición fluida entre datasets',              category:'scatter',  builder:() => const FlA19()),
    ChartItem(id:'fl_a20', title:'Scatter con Zoom',         subtitle:'Pinch zoom libre',                              category:'scatter',  builder:() => const FlA20()),
    ChartItem(id:'fl_a21', title:'Línea de Regresión',       subtitle:'Tendencia lineal superpuesta',                  category:'scatter',  builder:() => const FlA21()),
    ChartItem(id:'fl_a22', title:'Radar Animado',            subtitle:'Stats con entrada progresiva',                  category:'radar',    builder:() => const FlA22()),
    ChartItem(id:'fl_a23', title:'Radar Triple',             subtitle:'Tres Pokémon en un mismo radar',                category:'radar',    builder:() => const FlA23()),
    ChartItem(id:'fl_a24', title:'Radar por Tipo',           subtitle:'Colores según el tipo del Pokémon',             category:'radar',    builder:() => const FlA24()),
    ChartItem(id:'fl_a25', title:'Radar Interactivo',        subtitle:'Selector de Pokémon con botones',               category:'radar',    builder:() => const FlA25()),
    ChartItem(id:'fl_a26', title:'Burbujas Escalonadas',     subtitle:'Aparición animada una por una',                 category:'bubble',   builder:() => const FlA26()),
    ChartItem(id:'fl_a27', title:'Burbujas Interactivas',    subtitle:'Tap para ver datos del Pokémon',                category:'bubble',   builder:() => const FlA27()),
    ChartItem(id:'fl_a28', title:'Burbujas por Tipo',        subtitle:'Coloreadas por tipo Pokémon',                   category:'bubble',   builder:() => const FlA28()),
    ChartItem(id:'fl_a29', title:'Heatmap Interactivo',      subtitle:'Tap en celda para ver valor exacto',            category:'heatmap',  builder:() => const FlA29()),
    ChartItem(id:'fl_a30', title:'Heatmap Gradiente',        subtitle:'Paleta de colores personalizada',               category:'heatmap',  builder:() => const FlA30()),
    ChartItem(id:'fl_a31', title:'Área Apilada Animada',     subtitle:'Stats acumulados con animación',                category:'area',     builder:() => const FlA31()),
    ChartItem(id:'fl_a32', title:'Área con Threshold',       subtitle:'Línea de referencia al promedio',               category:'area',     builder:() => const FlA32()),
    ChartItem(id:'fl_a33', title:'Dashboard Completo',       subtitle:'Vista integral de un Pokémon',                  category:'combined', builder:() => const FlA33()),
    ChartItem(id:'fl_a34', title:'Comparador Lado a Lado',   subtitle:'Dos Pokémon en paralelo',                       category:'combined', builder:() => const FlA34()),
    ChartItem(id:'fl_a35', title:'Timeline Evolutivo',       subtitle:'Niveles de evolución tipo Gantt',               category:'combined', builder:() => const FlA35()),
    ChartItem(id:'fl_a36', title:'Waterfall Stats',          subtitle:'Diferencia acumulada de stats',                 category:'combined', builder:() => const FlA36()),
  ];

  // ── Syncfusion Basic (43) ───────────────────────────────────────────────────
  static final List<ChartItem> _sfBasic = [
    ChartItem(id:'sf_b01', title:'Stats de Bulbasaur',          subtitle:'Barras verticales · 6 stats base',               category:'bar',       builder:() => const SfB01()),
    ChartItem(id:'sf_b02', title:'Stats de Mewtwo',             subtitle:'Barras verticales · Pokémon legendario',          category:'bar',       builder:() => const SfB02()),
    ChartItem(id:'sf_b03', title:'Bulbasaur vs Charmander',     subtitle:'Barras agrupadas · Comparativa de stats',         category:'bar',       builder:() => const SfB03()),
    ChartItem(id:'sf_b04', title:'Top 5 por Ataque',            subtitle:'Barras horizontales · Ranking ofensivo',          category:'bar',       builder:() => const SfB04()),
    ChartItem(id:'sf_b05', title:'Top 5 por Defensa',           subtitle:'Barras horizontales · Ranking defensivo',         category:'bar',       builder:() => const SfB05()),
    ChartItem(id:'sf_b06', title:'Top 5 por HP',                subtitle:'Barras horizontales · Ranking de vida',           category:'bar',       builder:() => const SfB06()),
    ChartItem(id:'sf_b07', title:'Top 5 por Velocidad',         subtitle:'Barras horizontales · Ranking de velocidad',      category:'bar',       builder:() => const SfB07()),
    ChartItem(id:'sf_b08', title:'Fuego vs Agua vs Planta',     subtitle:'Barras agrupadas · Stats promedio por tipo',      category:'bar',       builder:() => const SfB08()),
    ChartItem(id:'sf_b09', title:'Evolución HP Bulbasaur',      subtitle:'Línea · Bulbasaur → Ivysaur → Venusaur',          category:'line',      builder:() => const SfB09()),
    ChartItem(id:'sf_b10', title:'Evolución Ataque Charmander', subtitle:'Línea · Charmander → Charizard',                  category:'line',      builder:() => const SfB10()),
    ChartItem(id:'sf_b11', title:'Evolución Defensa Squirtle',  subtitle:'Línea · Squirtle → Blastoise',                    category:'line',      builder:() => const SfB11()),
    ChartItem(id:'sf_b12', title:'HP Primeros 20 Pokémon',      subtitle:'Línea · Valores de HP Gen I',                     category:'line',      builder:() => const SfB12()),
    ChartItem(id:'sf_b13', title:'Velocidad Primeros 20',       subtitle:'Línea · Valores de velocidad Gen I',              category:'line',      builder:() => const SfB13()),
    ChartItem(id:'sf_b14', title:'Distribución Tipos Gen I',    subtitle:'Pastel · 8 categorías principales',               category:'pie',       builder:() => const SfB14()),
    ChartItem(id:'sf_b15', title:'Top 5 Tipos más Comunes',     subtitle:'Pastel · Los 5 tipos más frecuentes',             category:'pie',       builder:() => const SfB15()),
    ChartItem(id:'sf_b16', title:'Tipos Gen I (Donut)',          subtitle:'Donut · Proporción de cada tipo',                 category:'pie',       builder:() => const SfB16()),
    ChartItem(id:'sf_b17', title:'1 Tipo vs 2 Tipos',           subtitle:'Donut · Pokémon monotipo vs bitipo',              category:'pie',       builder:() => const SfB17()),
    ChartItem(id:'sf_b18', title:'Legendarios vs Normales',     subtitle:'Pastel · 5 legendarios vs 146 regulares',         category:'pie',       builder:() => const SfB18()),
    ChartItem(id:'sf_b19', title:'HP de los Starters',          subtitle:'Área · Los 9 starters de Gen I',                  category:'area',      builder:() => const SfB19()),
    ChartItem(id:'sf_b20', title:'Ataque Primeros 15',          subtitle:'Área · Evolución del ataque',                     category:'area',      builder:() => const SfB20()),
    ChartItem(id:'sf_b21', title:'HP Comparativa Starters',     subtitle:'Área multi-serie · Tres líneas evolutivas',       category:'area',      builder:() => const SfB21()),
    ChartItem(id:'sf_b22', title:'Defensa Primeros 20',         subtitle:'Área · Valores de defensa',                       category:'area',      builder:() => const SfB22()),
    ChartItem(id:'sf_b23', title:'Sp. Ataque Primeros 20',      subtitle:'Área · Ataque especial',                          category:'area',      builder:() => const SfB23()),
    ChartItem(id:'sf_b24', title:'Distribución HP Gen I',       subtitle:'Histograma · Rangos de puntos de vida',           category:'histogram', builder:() => const SfB24()),
    ChartItem(id:'sf_b25', title:'Distribución Ataque',         subtitle:'Histograma · Rangos de ataque',                   category:'histogram', builder:() => const SfB25()),
    ChartItem(id:'sf_b26', title:'Distribución Defensa',        subtitle:'Histograma · Rangos de defensa',                  category:'histogram', builder:() => const SfB26()),
    ChartItem(id:'sf_b27', title:'Distribución Velocidad',      subtitle:'Histograma · Rangos de velocidad',                category:'histogram', builder:() => const SfB27()),
    ChartItem(id:'sf_b28', title:'Ataque vs Defensa',           subtitle:'Dispersión · 40 Pokémon representativos',         category:'scatter',   builder:() => const SfB28()),
    ChartItem(id:'sf_b29', title:'HP vs Velocidad',             subtitle:'Dispersión · HP frente a velocidad',              category:'scatter',   builder:() => const SfB29()),
    ChartItem(id:'sf_b30', title:'Ataque vs Velocidad',         subtitle:'Dispersión · Perfil ofensivo',                    category:'scatter',   builder:() => const SfB30()),
    ChartItem(id:'sf_b31', title:'Sp.Atk vs Sp.Def',           subtitle:'Dispersión · Stats especiales',                   category:'scatter',   builder:() => const SfB31()),
    ChartItem(id:'sf_b32', title:'HP vs Ataque',                subtitle:'Burbuja · Tamaño representa Defensa',             category:'bubble',    builder:() => const SfB32()),
    ChartItem(id:'sf_b33', title:'Velocidad vs Ataque',         subtitle:'Burbuja · Tamaño representa HP',                  category:'bubble',    builder:() => const SfB33()),
    ChartItem(id:'sf_b34', title:'HP vs Sp.Atk',               subtitle:'Burbuja · Tamaño representa Velocidad',           category:'bubble',    builder:() => const SfB34()),
    ChartItem(id:'sf_b35', title:'Stats de Pikachu',            subtitle:'Radar · 6 dimensiones del ratón eléctrico',       category:'radar',     builder:() => const SfB35()),
    ChartItem(id:'sf_b36', title:'Stats de Mewtwo',             subtitle:'Radar · El Pokémon más poderoso',                 category:'radar',     builder:() => const SfB36()),
    ChartItem(id:'sf_b37', title:'Charizard vs Blastoise',      subtitle:'Radar multi-serie · Comparativa directa',         category:'radar',     builder:() => const SfB37()),
    ChartItem(id:'sf_b38', title:'Fuego avg vs Agua avg',       subtitle:'Radar · Promedios por tipo',                      category:'radar',     builder:() => const SfB38()),
    ChartItem(id:'sf_b39', title:'Correlación Stats Gen I',     subtitle:'Mapa de calor · Matriz 6×6',                      category:'heatmap',   builder:() => const SfB39()),
    ChartItem(id:'sf_b40', title:'Stats Promedio por Tipo',     subtitle:'Mapa de calor · 6 tipos × 6 stats',              category:'heatmap',   builder:() => const SfB40()),
    ChartItem(id:'sf_b41', title:'Stats + Línea Promedio',      subtitle:'Combinado · Barras con tendencia',                category:'combined',  builder:() => const SfB41()),
    ChartItem(id:'sf_b42', title:'HP Área + Velocidad Scatter', subtitle:'Combinado · Dos tipos de gráfica',                category:'combined',  builder:() => const SfB42()),
    ChartItem(id:'sf_b43', title:'Dashboard Pokémon',           subtitle:'Combinado · Stats, tipo y total',                 category:'combined',  builder:() => const SfB43()),
  ];

  // ── Syncfusion Advanced (36) ────────────────────────────────────────────────
  static final List<ChartItem> _sfAdvanced = [
    ChartItem(id:'sf_a01', title:'Barras Animadas',          subtitle:'Entrada con animación suave por stat',          category:'bar',      builder:() => const SfA01()),
    ChartItem(id:'sf_a02', title:'Selector de Pokémon',      subtitle:'Barras interactivas con dropdown',              category:'bar',      builder:() => const SfA02()),
    ChartItem(id:'sf_a03', title:'Barras con Tooltip',       subtitle:'Stats detallados al tocar la barra',            category:'bar',      builder:() => const SfA03()),
    ChartItem(id:'sf_a04', title:'Diferencia vs Promedio',   subtitle:'Barras positivas y negativas',                  category:'bar',      builder:() => const SfA04()),
    ChartItem(id:'sf_a05', title:'Composición 100%',         subtitle:'Barras apiladas normalizadas',                  category:'bar',      builder:() => const SfA05()),
    ChartItem(id:'sf_a06', title:'Ranking Dinámico Top 10',  subtitle:'Barras ordenadas por stat seleccionado',        category:'bar',      builder:() => const SfA06()),
    ChartItem(id:'sf_a07', title:'Línea con Zoom/Pan',       subtitle:'Navegación táctil interactiva',                 category:'line',     builder:() => const SfA07()),
    ChartItem(id:'sf_a08', title:'Multi-serie 6 Stats',      subtitle:'Todas las dimensiones a la vez',                category:'line',     builder:() => const SfA08()),
    ChartItem(id:'sf_a09', title:'Línea con Gradiente',      subtitle:'HP con fill degradado animado',                 category:'line',     builder:() => const SfA09()),
    ChartItem(id:'sf_a10', title:'Actualización Animada',    subtitle:'Datos simulados en tiempo real',                category:'line',     builder:() => const SfA10()),
    ChartItem(id:'sf_a11', title:'Comparativa Evolutiva',    subtitle:'Selector de línea evolutiva',                   category:'line',     builder:() => const SfA11()),
    ChartItem(id:'sf_a12', title:'Pastel Animado',           subtitle:'Entrada con animación circular',                category:'pie',      builder:() => const SfA12()),
    ChartItem(id:'sf_a13', title:'Leyenda Interactiva',      subtitle:'Toggle de secciones al tocar',                  category:'pie',      builder:() => const SfA13()),
    ChartItem(id:'sf_a14', title:'Donut con Estadística',    subtitle:'Total de stats en el centro',                   category:'pie',      builder:() => const SfA14()),
    ChartItem(id:'sf_a15', title:'Donut Multi-nivel',        subtitle:'Dos anillos de datos concéntricos',             category:'pie',      builder:() => const SfA15()),
    ChartItem(id:'sf_a16', title:'Semi-Donut Gauge',         subtitle:'Estilo medidor semicircular',                   category:'pie',      builder:() => const SfA16()),
    ChartItem(id:'sf_a17', title:'Scatter por Tipo',         subtitle:'Puntos coloreados por tipo Pokémon',            category:'scatter',  builder:() => const SfA17()),
    ChartItem(id:'sf_a18', title:'Scatter con Detalle',      subtitle:'Tap para ver nombre del Pokémon',               category:'scatter',  builder:() => const SfA18()),
    ChartItem(id:'sf_a19', title:'Scatter Animado',          subtitle:'Transición fluida entre datasets',              category:'scatter',  builder:() => const SfA19()),
    ChartItem(id:'sf_a20', title:'Scatter con Zoom',         subtitle:'Pinch zoom libre',                              category:'scatter',  builder:() => const SfA20()),
    ChartItem(id:'sf_a21', title:'Línea de Regresión',       subtitle:'Tendencia lineal superpuesta',                  category:'scatter',  builder:() => const SfA21()),
    ChartItem(id:'sf_a22', title:'Radar Animado',            subtitle:'Stats con entrada progresiva',                  category:'radar',    builder:() => const SfA22()),
    ChartItem(id:'sf_a23', title:'Radar Triple',             subtitle:'Tres Pokémon en un mismo radar',                category:'radar',    builder:() => const SfA23()),
    ChartItem(id:'sf_a24', title:'Radar por Tipo',           subtitle:'Colores según el tipo del Pokémon',             category:'radar',    builder:() => const SfA24()),
    ChartItem(id:'sf_a25', title:'Radar Interactivo',        subtitle:'Selector de Pokémon con botones',               category:'radar',    builder:() => const SfA25()),
    ChartItem(id:'sf_a26', title:'Burbujas Escalonadas',     subtitle:'Aparición animada una por una',                 category:'bubble',   builder:() => const SfA26()),
    ChartItem(id:'sf_a27', title:'Burbujas Interactivas',    subtitle:'Tap para ver datos del Pokémon',                category:'bubble',   builder:() => const SfA27()),
    ChartItem(id:'sf_a28', title:'Burbujas por Tipo',        subtitle:'Coloreadas por tipo Pokémon',                   category:'bubble',   builder:() => const SfA28()),
    ChartItem(id:'sf_a29', title:'Heatmap Interactivo',      subtitle:'Tap en celda para ver valor exacto',            category:'heatmap',  builder:() => const SfA29()),
    ChartItem(id:'sf_a30', title:'Heatmap Gradiente',        subtitle:'Paleta de colores personalizada',               category:'heatmap',  builder:() => const SfA30()),
    ChartItem(id:'sf_a31', title:'Área Apilada Animada',     subtitle:'Stats acumulados con animación',                category:'area',     builder:() => const SfA31()),
    ChartItem(id:'sf_a32', title:'Área con Threshold',       subtitle:'Línea de referencia al promedio',               category:'area',     builder:() => const SfA32()),
    ChartItem(id:'sf_a33', title:'Dashboard Completo',       subtitle:'Vista integral de un Pokémon',                  category:'combined', builder:() => const SfA33()),
    ChartItem(id:'sf_a34', title:'Comparador Lado a Lado',   subtitle:'Dos Pokémon en paralelo',                       category:'combined', builder:() => const SfA34()),
    ChartItem(id:'sf_a35', title:'Timeline Evolutivo',       subtitle:'Niveles de evolución tipo Gantt',               category:'combined', builder:() => const SfA35()),
    ChartItem(id:'sf_a36', title:'Waterfall Stats',          subtitle:'Diferencia acumulada de stats',                 category:'combined', builder:() => const SfA36()),
  ];

  // ── Graphic Basic (43) ──────────────────────────────────────────────────────
  static final List<ChartItem> _grBasic = [
    ChartItem(id:'gr_b01', title:'Stats de Bulbasaur',          subtitle:'Barras verticales · 6 stats base',               category:'bar',       builder:() => const GrB01()),
    ChartItem(id:'gr_b02', title:'Stats de Mewtwo',             subtitle:'Barras verticales · Pokémon legendario',          category:'bar',       builder:() => const GrB02()),
    ChartItem(id:'gr_b03', title:'Bulbasaur vs Charmander',     subtitle:'Barras agrupadas · Comparativa de stats',         category:'bar',       builder:() => const GrB03()),
    ChartItem(id:'gr_b04', title:'Top 5 por Ataque',            subtitle:'Barras horizontales · Ranking ofensivo',          category:'bar',       builder:() => const GrB04()),
    ChartItem(id:'gr_b05', title:'Top 5 por Defensa',           subtitle:'Barras horizontales · Ranking defensivo',         category:'bar',       builder:() => const GrB05()),
    ChartItem(id:'gr_b06', title:'Top 5 por HP',                subtitle:'Barras horizontales · Ranking de vida',           category:'bar',       builder:() => const GrB06()),
    ChartItem(id:'gr_b07', title:'Top 5 por Velocidad',         subtitle:'Barras horizontales · Ranking de velocidad',      category:'bar',       builder:() => const GrB07()),
    ChartItem(id:'gr_b08', title:'Fuego vs Agua vs Planta',     subtitle:'Barras agrupadas · Stats promedio por tipo',      category:'bar',       builder:() => const GrB08()),
    ChartItem(id:'gr_b09', title:'Evolución HP Bulbasaur',      subtitle:'Línea · Bulbasaur → Ivysaur → Venusaur',          category:'line',      builder:() => const GrB09()),
    ChartItem(id:'gr_b10', title:'Evolución Ataque Charmander', subtitle:'Línea · Charmander → Charizard',                  category:'line',      builder:() => const GrB10()),
    ChartItem(id:'gr_b11', title:'Evolución Defensa Squirtle',  subtitle:'Línea · Squirtle → Blastoise',                    category:'line',      builder:() => const GrB11()),
    ChartItem(id:'gr_b12', title:'HP Primeros 20 Pokémon',      subtitle:'Línea · Valores de HP Gen I',                     category:'line',      builder:() => const GrB12()),
    ChartItem(id:'gr_b13', title:'Velocidad Primeros 20',       subtitle:'Línea · Valores de velocidad Gen I',              category:'line',      builder:() => const GrB13()),
    ChartItem(id:'gr_b14', title:'Distribución Tipos Gen I',    subtitle:'Pastel · 8 categorías principales',               category:'pie',       builder:() => const GrB14()),
    ChartItem(id:'gr_b15', title:'Top 5 Tipos más Comunes',     subtitle:'Pastel · Los 5 tipos más frecuentes',             category:'pie',       builder:() => const GrB15()),
    ChartItem(id:'gr_b16', title:'Tipos Gen I (Donut)',          subtitle:'Donut · Proporción de cada tipo',                 category:'pie',       builder:() => const GrB16()),
    ChartItem(id:'gr_b17', title:'1 Tipo vs 2 Tipos',           subtitle:'Donut · Pokémon monotipo vs bitipo',              category:'pie',       builder:() => const GrB17()),
    ChartItem(id:'gr_b18', title:'Legendarios vs Normales',     subtitle:'Pastel · 5 legendarios vs 146 regulares',         category:'pie',       builder:() => const GrB18()),
    ChartItem(id:'gr_b19', title:'HP de los Starters',          subtitle:'Área · Los 9 starters de Gen I',                  category:'area',      builder:() => const GrB19()),
    ChartItem(id:'gr_b20', title:'Ataque Primeros 15',          subtitle:'Área · Evolución del ataque',                     category:'area',      builder:() => const GrB20()),
    ChartItem(id:'gr_b21', title:'HP Comparativa Starters',     subtitle:'Área multi-serie · Tres líneas evolutivas',       category:'area',      builder:() => const GrB21()),
    ChartItem(id:'gr_b22', title:'Defensa Primeros 20',         subtitle:'Área · Valores de defensa',                       category:'area',      builder:() => const GrB22()),
    ChartItem(id:'gr_b23', title:'Sp. Ataque Primeros 20',      subtitle:'Área · Ataque especial',                          category:'area',      builder:() => const GrB23()),
    ChartItem(id:'gr_b24', title:'Distribución HP Gen I',       subtitle:'Histograma · Rangos de puntos de vida',           category:'histogram', builder:() => const GrB24()),
    ChartItem(id:'gr_b25', title:'Distribución Ataque',         subtitle:'Histograma · Rangos de ataque',                   category:'histogram', builder:() => const GrB25()),
    ChartItem(id:'gr_b26', title:'Distribución Defensa',        subtitle:'Histograma · Rangos de defensa',                  category:'histogram', builder:() => const GrB26()),
    ChartItem(id:'gr_b27', title:'Distribución Velocidad',      subtitle:'Histograma · Rangos de velocidad',                category:'histogram', builder:() => const GrB27()),
    ChartItem(id:'gr_b28', title:'Ataque vs Defensa',           subtitle:'Dispersión · 40 Pokémon representativos',         category:'scatter',   builder:() => const GrB28()),
    ChartItem(id:'gr_b29', title:'HP vs Velocidad',             subtitle:'Dispersión · HP frente a velocidad',              category:'scatter',   builder:() => const GrB29()),
    ChartItem(id:'gr_b30', title:'Ataque vs Velocidad',         subtitle:'Dispersión · Perfil ofensivo',                    category:'scatter',   builder:() => const GrB30()),
    ChartItem(id:'gr_b31', title:'Sp.Atk vs Sp.Def',           subtitle:'Dispersión · Stats especiales',                   category:'scatter',   builder:() => const GrB31()),
    ChartItem(id:'gr_b32', title:'HP vs Ataque',                subtitle:'Burbuja · Tamaño representa Defensa',             category:'bubble',    builder:() => const GrB32()),
    ChartItem(id:'gr_b33', title:'Velocidad vs Ataque',         subtitle:'Burbuja · Tamaño representa HP',                  category:'bubble',    builder:() => const GrB33()),
    ChartItem(id:'gr_b34', title:'HP vs Sp.Atk',               subtitle:'Burbuja · Tamaño representa Velocidad',           category:'bubble',    builder:() => const GrB34()),
    ChartItem(id:'gr_b35', title:'Stats de Pikachu',            subtitle:'Radar · 6 dimensiones del ratón eléctrico',       category:'radar',     builder:() => const GrB35()),
    ChartItem(id:'gr_b36', title:'Stats de Mewtwo',             subtitle:'Radar · El Pokémon más poderoso',                 category:'radar',     builder:() => const GrB36()),
    ChartItem(id:'gr_b37', title:'Charizard vs Blastoise',      subtitle:'Radar multi-serie · Comparativa directa',         category:'radar',     builder:() => const GrB37()),
    ChartItem(id:'gr_b38', title:'Fuego avg vs Agua avg',       subtitle:'Radar · Promedios por tipo',                      category:'radar',     builder:() => const GrB38()),
    ChartItem(id:'gr_b39', title:'Correlación Stats Gen I',     subtitle:'Mapa de calor · Matriz 6×6',                      category:'heatmap',   builder:() => const GrB39()),
    ChartItem(id:'gr_b40', title:'Stats Promedio por Tipo',     subtitle:'Mapa de calor · 6 tipos × 6 stats',              category:'heatmap',   builder:() => const GrB40()),
    ChartItem(id:'gr_b41', title:'Stats + Línea Promedio',      subtitle:'Combinado · Barras con tendencia',                category:'combined',  builder:() => const GrB41()),
    ChartItem(id:'gr_b42', title:'HP Área + Velocidad Scatter', subtitle:'Combinado · Dos tipos de gráfica',                category:'combined',  builder:() => const GrB42()),
    ChartItem(id:'gr_b43', title:'Dashboard Pokémon',           subtitle:'Combinado · Stats, tipo y total',                 category:'combined',  builder:() => const GrB43()),
  ];

  // ── Graphic Advanced (36) ───────────────────────────────────────────────────
  static final List<ChartItem> _grAdvanced = [
    ChartItem(id:'gr_a01', title:'Barras Animadas',          subtitle:'Entrada con animación suave por stat',          category:'bar',      builder:() => const GrA01()),
    ChartItem(id:'gr_a02', title:'Selector de Pokémon',      subtitle:'Barras interactivas con dropdown',              category:'bar',      builder:() => const GrA02()),
    ChartItem(id:'gr_a03', title:'Barras con Tooltip',       subtitle:'Stats detallados al tocar la barra',            category:'bar',      builder:() => const GrA03()),
    ChartItem(id:'gr_a04', title:'Diferencia vs Promedio',   subtitle:'Barras positivas y negativas',                  category:'bar',      builder:() => const GrA04()),
    ChartItem(id:'gr_a05', title:'Composición 100%',         subtitle:'Barras apiladas normalizadas',                  category:'bar',      builder:() => const GrA05()),
    ChartItem(id:'gr_a06', title:'Ranking Dinámico Top 10',  subtitle:'Barras ordenadas por stat seleccionado',        category:'bar',      builder:() => const GrA06()),
    ChartItem(id:'gr_a07', title:'Línea con Zoom/Pan',       subtitle:'Navegación táctil interactiva',                 category:'line',     builder:() => const GrA07()),
    ChartItem(id:'gr_a08', title:'Multi-serie 6 Stats',      subtitle:'Todas las dimensiones a la vez',                category:'line',     builder:() => const GrA08()),
    ChartItem(id:'gr_a09', title:'Línea con Gradiente',      subtitle:'HP con fill degradado animado',                 category:'line',     builder:() => const GrA09()),
    ChartItem(id:'gr_a10', title:'Actualización Animada',    subtitle:'Datos simulados en tiempo real',                category:'line',     builder:() => const GrA10()),
    ChartItem(id:'gr_a11', title:'Comparativa Evolutiva',    subtitle:'Selector de línea evolutiva',                   category:'line',     builder:() => const GrA11()),
    ChartItem(id:'gr_a12', title:'Pastel Animado',           subtitle:'Entrada con animación circular',                category:'pie',      builder:() => const GrA12()),
    ChartItem(id:'gr_a13', title:'Leyenda Interactiva',      subtitle:'Toggle de secciones al tocar',                  category:'pie',      builder:() => const GrA13()),
    ChartItem(id:'gr_a14', title:'Donut con Estadística',    subtitle:'Total de stats en el centro',                   category:'pie',      builder:() => const GrA14()),
    ChartItem(id:'gr_a15', title:'Donut Multi-nivel',        subtitle:'Dos anillos de datos concéntricos',             category:'pie',      builder:() => const GrA15()),
    ChartItem(id:'gr_a16', title:'Semi-Donut Gauge',         subtitle:'Estilo medidor semicircular',                   category:'pie',      builder:() => const GrA16()),
    ChartItem(id:'gr_a17', title:'Scatter por Tipo',         subtitle:'Puntos coloreados por tipo Pokémon',            category:'scatter',  builder:() => const GrA17()),
    ChartItem(id:'gr_a18', title:'Scatter con Detalle',      subtitle:'Tap para ver nombre del Pokémon',               category:'scatter',  builder:() => const GrA18()),
    ChartItem(id:'gr_a19', title:'Scatter Animado',          subtitle:'Transición fluida entre datasets',              category:'scatter',  builder:() => const GrA19()),
    ChartItem(id:'gr_a20', title:'Scatter con Zoom',         subtitle:'Pinch zoom libre',                              category:'scatter',  builder:() => const GrA20()),
    ChartItem(id:'gr_a21', title:'Línea de Regresión',       subtitle:'Tendencia lineal superpuesta',                  category:'scatter',  builder:() => const GrA21()),
    ChartItem(id:'gr_a22', title:'Radar Animado',            subtitle:'Stats con entrada progresiva',                  category:'radar',    builder:() => const GrA22()),
    ChartItem(id:'gr_a23', title:'Radar Triple',             subtitle:'Tres Pokémon en un mismo radar',                category:'radar',    builder:() => const GrA23()),
    ChartItem(id:'gr_a24', title:'Radar por Tipo',           subtitle:'Colores según el tipo del Pokémon',             category:'radar',    builder:() => const GrA24()),
    ChartItem(id:'gr_a25', title:'Radar Interactivo',        subtitle:'Selector de Pokémon con botones',               category:'radar',    builder:() => const GrA25()),
    ChartItem(id:'gr_a26', title:'Burbujas Escalonadas',     subtitle:'Aparición animada una por una',                 category:'bubble',   builder:() => const GrA26()),
    ChartItem(id:'gr_a27', title:'Burbujas Interactivas',    subtitle:'Tap para ver datos del Pokémon',                category:'bubble',   builder:() => const GrA27()),
    ChartItem(id:'gr_a28', title:'Burbujas por Tipo',        subtitle:'Coloreadas por tipo Pokémon',                   category:'bubble',   builder:() => const GrA28()),
    ChartItem(id:'gr_a29', title:'Heatmap Interactivo',      subtitle:'Tap en celda para ver valor exacto',            category:'heatmap',  builder:() => const GrA29()),
    ChartItem(id:'gr_a30', title:'Heatmap Gradiente',        subtitle:'Paleta de colores personalizada',               category:'heatmap',  builder:() => const GrA30()),
    ChartItem(id:'gr_a31', title:'Área Apilada Animada',     subtitle:'Stats acumulados con animación',                category:'area',     builder:() => const GrA31()),
    ChartItem(id:'gr_a32', title:'Área con Threshold',       subtitle:'Línea de referencia al promedio',               category:'area',     builder:() => const GrA32()),
    ChartItem(id:'gr_a33', title:'Dashboard Completo',       subtitle:'Vista integral de un Pokémon',                  category:'combined', builder:() => const GrA33()),
    ChartItem(id:'gr_a34', title:'Comparador Lado a Lado',   subtitle:'Dos Pokémon en paralelo',                       category:'combined', builder:() => const GrA34()),
    ChartItem(id:'gr_a35', title:'Timeline Evolutivo',       subtitle:'Niveles de evolución tipo Gantt',               category:'combined', builder:() => const GrA35()),
    ChartItem(id:'gr_a36', title:'Waterfall Stats',          subtitle:'Diferencia acumulada de stats',                 category:'combined', builder:() => const GrA36()),
  ];

  // ── CustomPainter Basic (43) ────────────────────────────────────────────────
  static final List<ChartItem> _cpBasic = [
    ChartItem(id:'cp_b01', title:'Stats de Bulbasaur',          subtitle:'Barras verticales · 6 stats base',               category:'bar',       builder:() => const CpB01()),
    ChartItem(id:'cp_b02', title:'Stats de Mewtwo',             subtitle:'Barras verticales · Pokémon legendario',          category:'bar',       builder:() => const CpB02()),
    ChartItem(id:'cp_b03', title:'Bulbasaur vs Charmander',     subtitle:'Barras agrupadas · Comparativa de stats',         category:'bar',       builder:() => const CpB03()),
    ChartItem(id:'cp_b04', title:'Top 5 por Ataque',            subtitle:'Barras horizontales · Ranking ofensivo',          category:'bar',       builder:() => const CpB04()),
    ChartItem(id:'cp_b05', title:'Top 5 por Defensa',           subtitle:'Barras horizontales · Ranking defensivo',         category:'bar',       builder:() => const CpB05()),
    ChartItem(id:'cp_b06', title:'Top 5 por HP',                subtitle:'Barras horizontales · Ranking de vida',           category:'bar',       builder:() => const CpB06()),
    ChartItem(id:'cp_b07', title:'Top 5 por Velocidad',         subtitle:'Barras horizontales · Ranking de velocidad',      category:'bar',       builder:() => const CpB07()),
    ChartItem(id:'cp_b08', title:'Fuego vs Agua vs Planta',     subtitle:'Barras agrupadas · Stats promedio por tipo',      category:'bar',       builder:() => const CpB08()),
    ChartItem(id:'cp_b09', title:'Evolución HP Bulbasaur',      subtitle:'Línea · Bulbasaur → Ivysaur → Venusaur',          category:'line',      builder:() => const CpB09()),
    ChartItem(id:'cp_b10', title:'Evolución Ataque Charmander', subtitle:'Línea · Charmander → Charizard',                  category:'line',      builder:() => const CpB10()),
    ChartItem(id:'cp_b11', title:'Evolución Defensa Squirtle',  subtitle:'Línea · Squirtle → Blastoise',                    category:'line',      builder:() => const CpB11()),
    ChartItem(id:'cp_b12', title:'HP Primeros 20 Pokémon',      subtitle:'Línea · Valores de HP Gen I',                     category:'line',      builder:() => const CpB12()),
    ChartItem(id:'cp_b13', title:'Velocidad Primeros 20',       subtitle:'Línea · Valores de velocidad Gen I',              category:'line',      builder:() => const CpB13()),
    ChartItem(id:'cp_b14', title:'Distribución Tipos Gen I',    subtitle:'Pastel · 8 categorías principales',               category:'pie',       builder:() => const CpB14()),
    ChartItem(id:'cp_b15', title:'Top 5 Tipos más Comunes',     subtitle:'Pastel · Los 5 tipos más frecuentes',             category:'pie',       builder:() => const CpB15()),
    ChartItem(id:'cp_b16', title:'Tipos Gen I (Donut)',          subtitle:'Donut · Proporción de cada tipo',                 category:'pie',       builder:() => const CpB16()),
    ChartItem(id:'cp_b17', title:'1 Tipo vs 2 Tipos',           subtitle:'Donut · Pokémon monotipo vs bitipo',              category:'pie',       builder:() => const CpB17()),
    ChartItem(id:'cp_b18', title:'Legendarios vs Normales',     subtitle:'Pastel · 5 legendarios vs 146 regulares',         category:'pie',       builder:() => const CpB18()),
    ChartItem(id:'cp_b19', title:'HP de los Starters',          subtitle:'Área · Los 9 starters de Gen I',                  category:'area',      builder:() => const CpB19()),
    ChartItem(id:'cp_b20', title:'Ataque Primeros 15',          subtitle:'Área · Evolución del ataque',                     category:'area',      builder:() => const CpB20()),
    ChartItem(id:'cp_b21', title:'HP Comparativa Starters',     subtitle:'Área multi-serie · Tres líneas evolutivas',       category:'area',      builder:() => const CpB21()),
    ChartItem(id:'cp_b22', title:'Defensa Primeros 20',         subtitle:'Área · Valores de defensa',                       category:'area',      builder:() => const CpB22()),
    ChartItem(id:'cp_b23', title:'Sp. Ataque Primeros 20',      subtitle:'Área · Ataque especial',                          category:'area',      builder:() => const CpB23()),
    ChartItem(id:'cp_b24', title:'Distribución HP Gen I',       subtitle:'Histograma · Rangos de puntos de vida',           category:'histogram', builder:() => const CpB24()),
    ChartItem(id:'cp_b25', title:'Distribución Ataque',         subtitle:'Histograma · Rangos de ataque',                   category:'histogram', builder:() => const CpB25()),
    ChartItem(id:'cp_b26', title:'Distribución Defensa',        subtitle:'Histograma · Rangos de defensa',                  category:'histogram', builder:() => const CpB26()),
    ChartItem(id:'cp_b27', title:'Distribución Velocidad',      subtitle:'Histograma · Rangos de velocidad',                category:'histogram', builder:() => const CpB27()),
    ChartItem(id:'cp_b28', title:'Ataque vs Defensa',           subtitle:'Dispersión · 40 Pokémon representativos',         category:'scatter',   builder:() => const CpB28()),
    ChartItem(id:'cp_b29', title:'HP vs Velocidad',             subtitle:'Dispersión · HP frente a velocidad',              category:'scatter',   builder:() => const CpB29()),
    ChartItem(id:'cp_b30', title:'Ataque vs Velocidad',         subtitle:'Dispersión · Perfil ofensivo',                    category:'scatter',   builder:() => const CpB30()),
    ChartItem(id:'cp_b31', title:'Sp.Atk vs Sp.Def',           subtitle:'Dispersión · Stats especiales',                   category:'scatter',   builder:() => const CpB31()),
    ChartItem(id:'cp_b32', title:'HP vs Ataque',                subtitle:'Burbuja · Tamaño representa Defensa',             category:'bubble',    builder:() => const CpB32()),
    ChartItem(id:'cp_b33', title:'Velocidad vs Ataque',         subtitle:'Burbuja · Tamaño representa HP',                  category:'bubble',    builder:() => const CpB33()),
    ChartItem(id:'cp_b34', title:'HP vs Sp.Atk',               subtitle:'Burbuja · Tamaño representa Velocidad',           category:'bubble',    builder:() => const CpB34()),
    ChartItem(id:'cp_b35', title:'Stats de Pikachu',            subtitle:'Radar · 6 dimensiones del ratón eléctrico',       category:'radar',     builder:() => const CpB35()),
    ChartItem(id:'cp_b36', title:'Stats de Mewtwo',             subtitle:'Radar · El Pokémon más poderoso',                 category:'radar',     builder:() => const CpB36()),
    ChartItem(id:'cp_b37', title:'Charizard vs Blastoise',      subtitle:'Radar multi-serie · Comparativa directa',         category:'radar',     builder:() => const CpB37()),
    ChartItem(id:'cp_b38', title:'Fuego avg vs Agua avg',       subtitle:'Radar · Promedios por tipo',                      category:'radar',     builder:() => const CpB38()),
    ChartItem(id:'cp_b39', title:'Correlación Stats Gen I',     subtitle:'Mapa de calor · Matriz 6×6',                      category:'heatmap',   builder:() => const CpB39()),
    ChartItem(id:'cp_b40', title:'Stats Promedio por Tipo',     subtitle:'Mapa de calor · 6 tipos × 6 stats',              category:'heatmap',   builder:() => const CpB40()),
    ChartItem(id:'cp_b41', title:'Stats + Línea Promedio',      subtitle:'Combinado · Barras con tendencia',                category:'combined',  builder:() => const CpB41()),
    ChartItem(id:'cp_b42', title:'HP Área + Velocidad Scatter', subtitle:'Combinado · Dos tipos de gráfica',                category:'combined',  builder:() => const CpB42()),
    ChartItem(id:'cp_b43', title:'Dashboard Pokémon',           subtitle:'Combinado · Stats, tipo y total',                 category:'combined',  builder:() => const CpB43()),
  ];

  // ── CustomPainter Advanced (36) ─────────────────────────────────────────────
  static final List<ChartItem> _cpAdvanced = [
    ChartItem(id:'cp_a01', title:'Barras Animadas',          subtitle:'Entrada con animación suave por stat',          category:'bar',      builder:() => const CpA01()),
    ChartItem(id:'cp_a02', title:'Selector de Pokémon',      subtitle:'Barras interactivas con dropdown',              category:'bar',      builder:() => const CpA02()),
    ChartItem(id:'cp_a03', title:'Barras con Tooltip',       subtitle:'Stats detallados al tocar la barra',            category:'bar',      builder:() => const CpA03()),
    ChartItem(id:'cp_a04', title:'Diferencia vs Promedio',   subtitle:'Barras positivas y negativas',                  category:'bar',      builder:() => const CpA04()),
    ChartItem(id:'cp_a05', title:'Composición 100%',         subtitle:'Barras apiladas normalizadas',                  category:'bar',      builder:() => const CpA05()),
    ChartItem(id:'cp_a06', title:'Ranking Dinámico Top 10',  subtitle:'Barras ordenadas por stat seleccionado',        category:'bar',      builder:() => const CpA06()),
    ChartItem(id:'cp_a07', title:'Línea con Zoom/Pan',       subtitle:'Navegación táctil interactiva',                 category:'line',     builder:() => const CpA07()),
    ChartItem(id:'cp_a08', title:'Multi-serie 6 Stats',      subtitle:'Todas las dimensiones a la vez',                category:'line',     builder:() => const CpA08()),
    ChartItem(id:'cp_a09', title:'Línea con Gradiente',      subtitle:'HP con fill degradado animado',                 category:'line',     builder:() => const CpA09()),
    ChartItem(id:'cp_a10', title:'Actualización Animada',    subtitle:'Datos simulados en tiempo real',                category:'line',     builder:() => const CpA10()),
    ChartItem(id:'cp_a11', title:'Comparativa Evolutiva',    subtitle:'Selector de línea evolutiva',                   category:'line',     builder:() => const CpA11()),
    ChartItem(id:'cp_a12', title:'Pastel Animado',           subtitle:'Entrada con animación circular',                category:'pie',      builder:() => const CpA12()),
    ChartItem(id:'cp_a13', title:'Leyenda Interactiva',      subtitle:'Toggle de secciones al tocar',                  category:'pie',      builder:() => const CpA13()),
    ChartItem(id:'cp_a14', title:'Donut con Estadística',    subtitle:'Total de stats en el centro',                   category:'pie',      builder:() => const CpA14()),
    ChartItem(id:'cp_a15', title:'Donut Multi-nivel',        subtitle:'Dos anillos de datos concéntricos',             category:'pie',      builder:() => const CpA15()),
    ChartItem(id:'cp_a16', title:'Semi-Donut Gauge',         subtitle:'Estilo medidor semicircular',                   category:'pie',      builder:() => const CpA16()),
    ChartItem(id:'cp_a17', title:'Scatter por Tipo',         subtitle:'Puntos coloreados por tipo Pokémon',            category:'scatter',  builder:() => const CpA17()),
    ChartItem(id:'cp_a18', title:'Scatter con Detalle',      subtitle:'Tap para ver nombre del Pokémon',               category:'scatter',  builder:() => const CpA18()),
    ChartItem(id:'cp_a19', title:'Scatter Animado',          subtitle:'Transición fluida entre datasets',              category:'scatter',  builder:() => const CpA19()),
    ChartItem(id:'cp_a20', title:'Scatter con Zoom',         subtitle:'Pinch zoom libre',                              category:'scatter',  builder:() => const CpA20()),
    ChartItem(id:'cp_a21', title:'Línea de Regresión',       subtitle:'Tendencia lineal superpuesta',                  category:'scatter',  builder:() => const CpA21()),
    ChartItem(id:'cp_a22', title:'Radar Animado',            subtitle:'Stats con entrada progresiva',                  category:'radar',    builder:() => const CpA22()),
    ChartItem(id:'cp_a23', title:'Radar Triple',             subtitle:'Tres Pokémon en un mismo radar',                category:'radar',    builder:() => const CpA23()),
    ChartItem(id:'cp_a24', title:'Radar por Tipo',           subtitle:'Colores según el tipo del Pokémon',             category:'radar',    builder:() => const CpA24()),
    ChartItem(id:'cp_a25', title:'Radar Interactivo',        subtitle:'Selector de Pokémon con botones',               category:'radar',    builder:() => const CpA25()),
    ChartItem(id:'cp_a26', title:'Burbujas Escalonadas',     subtitle:'Aparición animada una por una',                 category:'bubble',   builder:() => const CpA26()),
    ChartItem(id:'cp_a27', title:'Burbujas Interactivas',    subtitle:'Tap para ver datos del Pokémon',                category:'bubble',   builder:() => const CpA27()),
    ChartItem(id:'cp_a28', title:'Burbujas por Tipo',        subtitle:'Coloreadas por tipo Pokémon',                   category:'bubble',   builder:() => const CpA28()),
    ChartItem(id:'cp_a29', title:'Heatmap Interactivo',      subtitle:'Tap en celda para ver valor exacto',            category:'heatmap',  builder:() => const CpA29()),
    ChartItem(id:'cp_a30', title:'Heatmap Gradiente',        subtitle:'Paleta de colores personalizada',               category:'heatmap',  builder:() => const CpA30()),
    ChartItem(id:'cp_a31', title:'Área Apilada Animada',     subtitle:'Stats acumulados con animación',                category:'area',     builder:() => const CpA31()),
    ChartItem(id:'cp_a32', title:'Área con Threshold',       subtitle:'Línea de referencia al promedio',               category:'area',     builder:() => const CpA32()),
    ChartItem(id:'cp_a33', title:'Dashboard Completo',       subtitle:'Vista integral de un Pokémon',                  category:'combined', builder:() => const CpA33()),
    ChartItem(id:'cp_a34', title:'Comparador Lado a Lado',   subtitle:'Dos Pokémon en paralelo',                       category:'combined', builder:() => const CpA34()),
    ChartItem(id:'cp_a35', title:'Timeline Evolutivo',       subtitle:'Niveles de evolución tipo Gantt',               category:'combined', builder:() => const CpA35()),
    ChartItem(id:'cp_a36', title:'Waterfall Stats',          subtitle:'Diferencia acumulada de stats',                 category:'combined', builder:() => const CpA36()),
  ];
}
